export const EMOJI_CATEGORIES = {
  'Emotion': [
    { shortcut: '/기쁨', emoji: '😀' },
    { shortcut: '/웃음', emoji: '😁' },
    { shortcut: '/폭소', emoji: '😂' },
    { shortcut: '/웃겨', emoji: '🤣' },
    { shortcut: '/긴장', emoji: '😅' },
    { shortcut: '/즐거움', emoji: '😆' },
    { shortcut: '/천사', emoji: '😇' },
    { shortcut: '/윙크', emoji: '😉' },
    { shortcut: '/미소', emoji: '😊' },
    { shortcut: '/맛있음', emoji: '😋' },
    { shortcut: '/사랑', emoji: '😍' },
    { shortcut: '/뽀뽀', emoji: '🥰' },
    { shortcut: '/키스', emoji: '😘' },
    { shortcut: '/뽀뽀', emoji: '😗' },
    { shortcut: '/뽀뽀', emoji: '😚' },
    { shortcut: '/뽀뽀2', emoji: '😙' },
    { shortcut: '/생각', emoji: '🤔' },
    { shortcut: '/의심', emoji: '🤨' },
    { shortcut: '/무표정', emoji: '😐' },
    { shortcut: '/무표정2', emoji: '😑' },
    { shortcut: '/말없음', emoji: '😶' },
    { shortcut: '/짜증', emoji: '🙄' },
    { shortcut: '/능글', emoji: '😏' },
    { shortcut: '/고통', emoji: '😣' },
    { shortcut: '/슬픔', emoji: '😥' },
    { shortcut: '/놀람', emoji: '😮' },
    { shortcut: '/놀람2', emoji: '😯' },
    { shortcut: '/졸림', emoji: '😪' },
    { shortcut: '/피곤', emoji: '😫' },
    { shortcut: '/잠', emoji: '😴' },
    { shortcut: '/안도', emoji: '😌' },
    { shortcut: '/장난', emoji: '😛' },
    { shortcut: '/윙크장난', emoji: '😜' },
    { shortcut: '/웃음폭발', emoji: '😝' },
    { shortcut: '/침흘림', emoji: '🤤' },
    { shortcut: '/짜증2', emoji: '😒' },
    { shortcut: '/땀', emoji: '😓' },
    { shortcut: '/슬픈', emoji: '😔' },
    { shortcut: '/혼란', emoji: '😕' },
    { shortcut: '/뒤집힌얼굴', emoji: '🙃' },
    { shortcut: '/돈', emoji: '🤑' },
    { shortcut: '/놀람3', emoji: '😲' },
    { shortcut: '/조용', emoji: '🤐' },
    { shortcut: '/화남', emoji: '😡' },
    { shortcut: '/욕', emoji: '🤬' },
    { shortcut: '/분노', emoji: '😠' },
    { shortcut: '/흥분', emoji: '😤' },
    { shortcut: '/눈물', emoji: '😢' },
    { shortcut: '/펑펑', emoji: '😭' },
    { shortcut: '/불안', emoji: '😦' },
    { shortcut: '/충격', emoji: '😧' },
    { shortcut: '/두려움', emoji: '😨' },
    { shortcut: '/긴장2', emoji: '😰' },
    { shortcut: '/공포', emoji: '😱' },
    { shortcut: '/당황', emoji: '😳' },
    { shortcut: '/어지러움', emoji: '😵' },
    { shortcut: '/혼란2', emoji: '😵‍💫' },
    { shortcut: '/더움', emoji: '🥵' },
    { shortcut: '/추움', emoji: '🥶' },
    { shortcut: '/취함', emoji: '🥴' },
  ],
  'PeopleBodyRoles': [
    { shortcut: "/손인사", emoji: "👋" },
    { shortcut: "/멈춤", emoji: "🤚" },
    { shortcut: "/손들기", emoji: "🖐" },
    { shortcut: "/손멈춤", emoji: "✋" },
    { shortcut: "/봉바다인사", emoji: "🖖" },
    { shortcut: "/괜찮아", emoji: "👌" },
    { shortcut: "/브이", emoji: "✌" },
    { shortcut: "/기대", emoji: "🤞" },
    { shortcut: "/사랑해", emoji: "🤟" },
    { shortcut: "/락", emoji: "🤘" },
    { shortcut: "/전화", emoji: "🤙" },
    { shortcut: "/욕", emoji: "🖕" },
    { shortcut: "/글쓰기", emoji: "✍️" },
    { shortcut: "/좋아", emoji: "👍" },
    { shortcut: "/싫어", emoji: "👎" },
    { shortcut: "/주먹", emoji: "👊" },
    { shortcut: "/강조", emoji: "✊" },
    { shortcut: "/왼주먹", emoji: "🤛" },
    { shortcut: "/오른주먹", emoji: "🤜" },
    { shortcut: "/만세", emoji: "🙌" },
    { shortcut: "/박수", emoji: "👏" },
    { shortcut: "/손펴기", emoji: "👐" },
    { shortcut: "/손바닥", emoji: "🤲" },
    { shortcut: "/기도", emoji: "🙏" },
    { shortcut: "/근육", emoji: "💪" },
    { shortcut: "/다리", emoji: "🦵" },
    { shortcut: "/발", emoji: "🦶" },
    { shortcut: "/귀", emoji: "👂" },
    { shortcut: "/코", emoji: "👃" },
    { shortcut: "/뇌", emoji: "🧠" },
    { shortcut: "/눈", emoji: "👀" },
    { shortcut: "/눈", emoji: "👁️" },
    { shortcut: "/혀", emoji: "👅" },
    { shortcut: "/입", emoji: "👄" },
    { shortcut: "/아기", emoji: "👶" },
    { shortcut: "/어린이", emoji: "🧒" },
    { shortcut: "/소년", emoji: "👦" },
    { shortcut: "/소녀", emoji: "👧" },
    { shortcut: "/사람", emoji: "🧑" },
    { shortcut: "/금발남", emoji: "👱‍♂️" },
    { shortcut: "/금발여", emoji: "👱‍♀️" },
    { shortcut: "/남자", emoji: "👨" },
    { shortcut: "/여자", emoji: "👩" },
    { shortcut: "/노인남", emoji: "👴" },
    { shortcut: "/노인여", emoji: "👵" },
    { shortcut: "/의사남", emoji: "👨‍⚕️" },
    { shortcut: "/의사여", emoji: "👩‍⚕️" },
    { shortcut: "/학생남", emoji: "👨‍🎓" },
    { shortcut: "/학생여", emoji: "👩‍🎓" },
    { shortcut: "/선생님남", emoji: "👨‍🏫" },
    { shortcut: "/선생님여", emoji: "👩‍🏫" },
    { shortcut: "/기술자남", emoji: "👨‍🔧" },
    { shortcut: "/기술자여", emoji: "👩‍🔧" },
    { shortcut: "/춤추기", emoji: "💃" },
    { shortcut: "/춤추기남", emoji: "🕺" },
    { shortcut: "/달리기남", emoji: "🏃‍♂️" },
    { shortcut: "/달리기여", emoji: "🏃‍♀️" },
    { shortcut: "/등산남", emoji: "🧗‍♂️" },
    { shortcut: "/등산여", emoji: "🧗‍♀️" },
    { shortcut: "/펜싱", emoji: "🤺" },
    { shortcut: "/싸움남", emoji: "🤼‍♂️" },
    { shortcut: "/싸움여", emoji: "🤼‍♀️" },
    { shortcut: "/근위병남", emoji: "💂‍♂️" },
    { shortcut: "/근위병여", emoji: "💂‍♀️" },
  ],
  'AnimalsAndNature': [
    { shortcut: "/강아지", emoji: "🐶" },
    { shortcut: "/고양이", emoji: "🐱" },
    { shortcut: "/쥐", emoji: "🐭" },
    { shortcut: "/햄스터", emoji: "🐹" },
    { shortcut: "/토끼", emoji: "🐰" },
    { shortcut: "/여우", emoji: "🦊" },
    { shortcut: "/곰", emoji: "🐻" },
    { shortcut: "/판다", emoji: "🐼" },
    { shortcut: "/코알라", emoji: "🐨" },
    { shortcut: "/호랑이", emoji: "🐯" },
    { shortcut: "/사자", emoji: "🦁" },
    { shortcut: "/소", emoji: "🐮" },
    { shortcut: "/돼지", emoji: "🐷" },
    { shortcut: "/개구리", emoji: "🐸" },
    { shortcut: "/원숭이", emoji: "🐵" },
    { shortcut: "/보지마", emoji: "🙈" },
    { shortcut: "/들어마", emoji: "🙉" },
    { shortcut: "/말하지마", emoji: "🙊" },
    { shortcut: "/유니콘", emoji: "🦄" },
    { shortcut: "/닭", emoji: "🐔" },
    { shortcut: "/백조", emoji: "🦢" },
    { shortcut: "/앵무새", emoji: "🦜" },
    { shortcut: "/홍학", emoji: "🦩" },
    { shortcut: "/나무늘보", emoji: "🦥" },
    { shortcut: "/수달", emoji: "🦦" },
    { shortcut: "/스컹크", emoji: "🦨" },
    { shortcut: "/캥거루", emoji: "🦘" },
    { shortcut: "/벌", emoji: "🐝" },
    { shortcut: "/애벌레", emoji: "🐛" },
    { shortcut: "/나비", emoji: "🦋" },
    { shortcut: "/달팽이", emoji: "🐌" },
    { shortcut: "/무당벌레", emoji: "🐞" },
    { shortcut: "/모기", emoji: "🦟" },
    { shortcut: "/귀뚜라미", emoji: "🦗" },
    { shortcut: "/거미", emoji: "🕷️" },
    { shortcut: "/전갈", emoji: "🦂" },
    { shortcut: "/게", emoji: "🦀" },
    { shortcut: "/바닷가재", emoji: "🦞" },
    { shortcut: "/새우", emoji: "🦐" },
    { shortcut: "/오징어", emoji: "🦑" },
    { shortcut: "/나무", emoji: "🌲" },
    { shortcut: "/대나무", emoji: "🌳" },
    { shortcut: "/야자수", emoji: "🌴" },
    { shortcut: "/선인장", emoji: "🌵" },
    { shortcut: "/해바라기", emoji: "🌻" },
    { shortcut: "/들꽃", emoji: "🌼" },
    { shortcut: "/벚꽃", emoji: "🌸" },
    { shortcut: "/꽃다발", emoji: "💐" },
    { shortcut: "/꽃", emoji: "🌺" },
    { shortcut: "/장미", emoji: "🌹" },
    { shortcut: "/시든꽃", emoji: "🥀" },
    { shortcut: "/논", emoji: "🌾" },
    { shortcut: "/클로버", emoji: "🍀" },
    { shortcut: "/단풍", emoji: "🍁" },
    { shortcut: "/떨어진잎", emoji: "🍂" },
    { shortcut: "/바람", emoji: "🍃" },
    { shortcut: "/지구", emoji: "🌍" },
    { shortcut: "/지구", emoji: "🌎" },
    { shortcut: "/지구", emoji: "🌏" },
    { shortcut: "/보름달", emoji: "🌕" },
    { shortcut: "/달", emoji: "🌖" },
    { shortcut: "/반달", emoji: "🌗" },
    { shortcut: "/초승달", emoji: "🌘" },
    { shortcut: "/초승달밤", emoji: "🌑" },
    { shortcut: "/초승달2", emoji: "🌒" },
    { shortcut: "/반달2", emoji: "🌓" },
    { shortcut: "/반달3", emoji: "🌔" },
    { shortcut: "/달", emoji: "🌙" },
    { shortcut: "/달밤", emoji: "🌚" },
  ],
  'FoodAndDrink': [
    { shortcut: "/초록사과", emoji: "🍏" },
    { shortcut: "/빨간사과", emoji: "🍎" },
    { shortcut: "/배", emoji: "🍐" },
    { shortcut: "/오렌지", emoji: "🍊" },
    { shortcut: "/레몬", emoji: "🍋" },
    { shortcut: "/바나나", emoji: "🍌" },
    { shortcut: "/수박", emoji: "🍉" },
    { shortcut: "/포도", emoji: "🍇" },
    { shortcut: "/딸기", emoji: "🍓" },
    { shortcut: "/멜론", emoji: "🍈" },
    { shortcut: "/체리", emoji: "🍒" },
    { shortcut: "/복숭아", emoji: "🍑" },
    { shortcut: "/망고", emoji: "🥭" },
    { shortcut: "/파인애플", emoji: "🍍" },
    { shortcut: "/코코넛", emoji: "🥥" },
    { shortcut: "/키위", emoji: "🥝" },
    { shortcut: "/아보카도", emoji: "🥑" },
    { shortcut: "/가지", emoji: "🍆" },
    { shortcut: "/감자", emoji: "🥔" },
    { shortcut: "/당근", emoji: "🥕" },
    { shortcut: "/옥수수", emoji: "🌽" },
    { shortcut: "/고추", emoji: "🌶️" },
    { shortcut: "/오이", emoji: "🥒" },
    { shortcut: "/상추", emoji: "🥬" },
    { shortcut: "/브로콜리", emoji: "🥦" },
    { shortcut: "/마늘", emoji: "🧄" },
    { shortcut: "/양파", emoji: "🧅" },
    { shortcut: "/버섯", emoji: "🍄" },
    { shortcut: "/땅콩", emoji: "🥜" },
    { shortcut: "/빵", emoji: "🍞" },
    { shortcut: "/크루아상", emoji: "🥐" },
    { shortcut: "/바게트", emoji: "🥖" },
    { shortcut: "/프레첼", emoji: "🥨" },
    { shortcut: "/베이글", emoji: "🥯" },
    { shortcut: "/팬케이크", emoji: "🥞" },
    { shortcut: "/와플", emoji: "🧇" },
    { shortcut: "/치즈", emoji: "🧀" },
    { shortcut: "/치킨", emoji: "🍗" },
    { shortcut: "/고기", emoji: "🍖" },
    { shortcut: "/스테이크", emoji: "🥩" },
    { shortcut: "/새우튀김", emoji: "🍤" },
    { shortcut: "/계란후라이", emoji: "🍳" },
    { shortcut: "/계란", emoji: "🥚" },
    { shortcut: "/햄버거", emoji: "🍔" },
    { shortcut: "/감자튀김", emoji: "🍟" },
    { shortcut: "/피자", emoji: "🍕" },
    { shortcut: "/핫도그", emoji: "🌭" },
    { shortcut: "/샌드위치", emoji: "🥪" },
    { shortcut: "/타코", emoji: "🌮" },
    { shortcut: "/부리또", emoji: "🌯" },
    { shortcut: "/랩", emoji: "🥙" },
    { shortcut: "/샐러드", emoji: "🥗" },
    { shortcut: "/케이크", emoji: "🍰" },
    { shortcut: "/생일케이크", emoji: "🎂" },
    { shortcut: "/푸딩", emoji: "🍮" },
    { shortcut: "/사탕", emoji: "🍭" },
    { shortcut: "/젤리", emoji: "🍬" },
    { shortcut: "/초콜릿", emoji: "🍫" },
    { shortcut: "/팝콘", emoji: "🍿" },
    { shortcut: "/도넛", emoji: "🍩" },
    { shortcut: "/쿠키", emoji: "🍪" },
    { shortcut: "/커피", emoji: "☕" },
    { shortcut: "/차", emoji: "🍵" },
    { shortcut: "/술", emoji: "🍶" },
    { shortcut: "/음료", emoji: "🥤" },
    { shortcut: "/과즙", emoji: "🧃" },
    { shortcut: "/우유", emoji: "🥛" },
    { shortcut: "/맥주", emoji: "🍺" },
    { shortcut: "/건배", emoji: "🍻" },
    { shortcut: "/와인", emoji: "🍷" },
    { shortcut: "/샴페인", emoji: "🥂" },
    { shortcut: "/칵테일", emoji: "🍸" },
    { shortcut: "/칵테일2", emoji: "🍹" },
  ],
  'TransportAndBuildings': [
    { shortcut: "/자동차", emoji: "🚗" },
    { shortcut: "/택시", emoji: "🚕" },
    { shortcut: "/SUV", emoji: "🚙" },
    { shortcut: "/버스", emoji: "🚌" },
    { shortcut: "/전차", emoji: "🚎" },
    { shortcut: "/레이싱카", emoji: "🏎️" },
    { shortcut: "/경찰차", emoji: "🚓" },
    { shortcut: "/구급차", emoji: "🚑" },
    { shortcut: "/소방차", emoji: "🚒" },
    { shortcut: "/미니밴", emoji: "🚐" },
    { shortcut: "/트럭", emoji: "🚚" },
    { shortcut: "/대형트럭", emoji: "🚛" },
    { shortcut: "/농기계", emoji: "🚜" },
    { shortcut: "/킥보드", emoji: "🛴" },
    { shortcut: "/자전거", emoji: "🚲" },
    { shortcut: "/스쿠터", emoji: "🛵" },
    { shortcut: "/오토바이", emoji: "🏍️" },
    { shortcut: "/사이렌", emoji: "🚨" },
    { shortcut: "/경찰", emoji: "🚔" },
    { shortcut: "/비행기", emoji: "✈️" },
    { shortcut: "/이륙", emoji: "🛫" },
    { shortcut: "/착륙", emoji: "🛬" },
    { shortcut: "/로켓", emoji: "🚀" },
    { shortcut: "/UFO", emoji: "🛸" },
    { shortcut: "/요트", emoji: "⛵" },
    { shortcut: "/카약", emoji: "🛶" },
    { shortcut: "/모터보트", emoji: "🚤" },
    { shortcut: "/요트2", emoji: "🛥️" },
    { shortcut: "/크루즈", emoji: "🛳️" },
    { shortcut: "/집", emoji: "🏠" },
    { shortcut: "/전원주택", emoji: "🏡" },
    { shortcut: "/빌딩", emoji: "🏢" },
    { shortcut: "/백화점", emoji: "🏬" },
    { shortcut: "/우체국", emoji: "🏣" },
    { shortcut: "/회사", emoji: "🏤" },
    { shortcut: "/병원", emoji: "🏥" },
    { shortcut: "/은행", emoji: "🏦" },
    { shortcut: "/호텔", emoji: "🏨" },
    { shortcut: "/편의점", emoji: "🏪" },
    { shortcut: "/학교", emoji: "🏫" },
    { shortcut: "/성", emoji: "🏰" },
    { shortcut: "/일본성", emoji: "🏯" },
    { shortcut: "/박물관", emoji: "🏛️" },
    { shortcut: "/자유의여신상", emoji: "🗽" },
    { shortcut: "/도쿄타워", emoji: "🗼" },
    { shortcut: "/후지산", emoji: "🗻" },
  ],
  'ActivitiesAndSports': [
    { shortcut: "/축구", emoji: "⚽" },
    { shortcut: "/농구", emoji: "🏀" },
    { shortcut: "/미식축구", emoji: "🏈" },
    { shortcut: "/야구", emoji: "⚾" },
    { shortcut: "/소프트볼", emoji: "🥎" },
    { shortcut: "/테니스", emoji: "🎾" },
    { shortcut: "/배구", emoji: "🏐" },
    { shortcut: "/럭비", emoji: "🏉" },
    { shortcut: "/당구", emoji: "🎱" },
    { shortcut: "/탁구", emoji: "🏓" },
    { shortcut: "/배드민턴", emoji: "🏸" },
    { shortcut: "/골대", emoji: "🥅" },
    { shortcut: "/하키", emoji: "🏒" },
    { shortcut: "/필드하키", emoji: "🏑" },
    { shortcut: "/라크로스", emoji: "🥍" },
    { shortcut: "/크리켓", emoji: "🏏" },
    { shortcut: "/역도남", emoji: "🏋️‍♂️" },
    { shortcut: "/역도여", emoji: "🏋️‍♀️" },
    { shortcut: "/자전거남", emoji: "🚴‍♂️" },
    { shortcut: "/자전거여", emoji: "🚴‍♀️" },
    { shortcut: "/수영남", emoji: "🏊‍♂️" },
    { shortcut: "/수영여", emoji: "🏊‍♀️" },
    { shortcut: "/수구남", emoji: "🤽‍♂️" },
    { shortcut: "/수구여", emoji: "🤽‍♀️" },
    { shortcut: "/핸드볼남", emoji: "🤾‍♂️" },
    { shortcut: "/핸드볼여", emoji: "🤾‍♀️" },
    { shortcut: "/명상남", emoji: "🧘‍♂️" },
    { shortcut: "/명상여", emoji: "🧘‍♀️" },
    { shortcut: "/서핑남", emoji: "🏄‍♂️" },
    { shortcut: "/서핑여", emoji: "🏄‍♀️" },
    { shortcut: "/등산남", emoji: "🧗‍♂️" },
    { shortcut: "/등산여", emoji: "🧗‍♀️" },
    { shortcut: "/경마", emoji: "🏇" },
    { shortcut: "/스키", emoji: "🎿" },
    { shortcut: "/스키2", emoji: "⛷️" },
    { shortcut: "/썰매", emoji: "🛷" },
    { shortcut: "/컬링", emoji: "🥌" },
    { shortcut: "/아이스스케이트", emoji: "⛸️" },
  ],
  'ObjectsAndTechnology': [
    { shortcut: "/휴대폰", emoji: "📱" },
    { shortcut: "/휴대폰2", emoji: "📲" },
    { shortcut: "/노트북", emoji: "💻" },
    { shortcut: "/데스크탑", emoji: "🖥️" },
    { shortcut: "/프린터", emoji: "🖨️" },
    { shortcut: "/마우스", emoji: "🖱️" },
    { shortcut: "/키보드", emoji: "⌨️" },
    { shortcut: "/펜", emoji: "🖊️" },
    { shortcut: "/펜2", emoji: "🖋️" },
    { shortcut: "/브러쉬", emoji: "🖌️" },
    { shortcut: "/크레용", emoji: "🖍️" },
    { shortcut: "/카메라", emoji: "📷" },
    { shortcut: "/카메라2", emoji: "📸" },
    { shortcut: "/비디오", emoji: "🎥" },
    { shortcut: "/비디오2", emoji: "📹" },
    { shortcut: "/영화필름", emoji: "🎞️" },
    { shortcut: "/시계", emoji: "🕰️" },
    { shortcut: "/알람시계", emoji: "⏰" },
    { shortcut: "/모래시계", emoji: "⏳" },
    { shortcut: "/모래시계2", emoji: "⌛" },
    { shortcut: "/나침반", emoji: "🧭" },
    { shortcut: "/지도", emoji: "🗺️" },
    { shortcut: "/공구상자", emoji: "🧰" },
    { shortcut: "/망치", emoji: "🔨" },
    { shortcut: "/공구", emoji: "🛠️" },
    { shortcut: "/자석", emoji: "🧲" },
    { shortcut: "/시험관", emoji: "🧪" },
    { shortcut: "/페트리접시", emoji: "🧫" },
    { shortcut: "/DNA", emoji: "🧬" },
    { shortcut: "/전구", emoji: "💡" },
    { shortcut: "/손전등", emoji: "🔦" },
    { shortcut: "/촛불", emoji: "🕯️" },
    { shortcut: "/기름통", emoji: "🛢️" },
    { shortcut: "/보석", emoji: "💎" },
    { shortcut: "/저울", emoji: "⚖️" },
    { shortcut: "/항아리", emoji: "🏺" },
    { shortcut: "/부적", emoji: "🧿" },
    { shortcut: "/벨", emoji: "🛎️" },
    { shortcut: "/열쇠", emoji: "🔑" },
    { shortcut: "/잠금", emoji: "🔒" },
    { shortcut: "/잠금해제", emoji: "🔓" },
  ],
  'SymbolsAndSigns': [
    { shortcut: "/하트", emoji: "❤️" },
    { shortcut: "/상심", emoji: "💔" },
    { shortcut: "/반짝하트", emoji: "❣️" },
    { shortcut: "/두하트", emoji: "💕" },
    { shortcut: "/돌아가는하트", emoji: "💞" },
    { shortcut: "/뛰는하트", emoji: "💓" },
    { shortcut: "/커지는하트", emoji: "💗" },
    { shortcut: "/반짝임", emoji: "💖" },
    { shortcut: "/화살표하트", emoji: "💘" },
    { shortcut: "/선물하트", emoji: "💝" },
    { shortcut: "/하트장식", emoji: "💟" },
    { shortcut: "/엑스", emoji: "❌" },
    { shortcut: "/체크", emoji: "✅" },
    { shortcut: "/완료", emoji: "✔️" },
    { shortcut: "/더하기", emoji: "➕" },
    { shortcut: "/빼기", emoji: "➖" },
    { shortcut: "/나누기", emoji: "➗" },
    { shortcut: "/물음표", emoji: "❓" },
    { shortcut: "/물음표2", emoji: "❔" },
    { shortcut: "/느낌표", emoji: "❕" },
    { shortcut: "/느낌표2", emoji: "❗" },
    { shortcut: "/평화", emoji: "☮️" },
    { shortcut: "/십자가", emoji: "✝️" },
    { shortcut: "/이슬람", emoji: "☪️" },
    { shortcut: "/오움", emoji: "🕉️" },
    { shortcut: "/법륜", emoji: "☸️" },
    { shortcut: "/별다윗", emoji: "✡️" },
    { shortcut: "/육각별", emoji: "🔯" },
    { shortcut: "/메노라", emoji: "🕎" },
    { shortcut: "/음양", emoji: "☯️" },
    { shortcut: "/동방정교", emoji: "☦️" },
    { shortcut: "/경고", emoji: "⚠️" },
    { shortcut: "/조심", emoji: "🚸" },
    { shortcut: "/재활용", emoji: "♻️" },
    { shortcut: "/완벽", emoji: "💯" },
    { shortcut: "/미성년자금지", emoji: "🔞" },
    { shortcut: "/음악", emoji: "🎵" },
    { shortcut: "/멜로디", emoji: "🎶" },
    { shortcut: "/악보", emoji: "🎼" },
    { shortcut: "/삼지창", emoji: "🔱" },
  ],
  'Flags': [
    { shortcut: "/백기", emoji: "🏳️" },
    { shortcut: "/검은기", emoji: "🏴" },
    { shortcut: "/깃발", emoji: "🚩" },
    { shortcut: "/대한민국", emoji: "🇰🇷" },
    { shortcut: "/미국", emoji: "🇺🇸" },
    { shortcut: "/일본", emoji: "🇯🇵" },
    { shortcut: "/중국", emoji: "🇨🇳" },
    { shortcut: "/프랑스", emoji: "🇫🇷" },
    { shortcut: "/독일", emoji: "🇩🇪" },
    { shortcut: "/영국", emoji: "🇬🇧" },
    { shortcut: "/스페인", emoji: "🇪🇸" },
    { shortcut: "/이탈리아", emoji: "🇮🇹" },
    { shortcut: "/러시아", emoji: "🇷🇺" },
    { shortcut: "/캐나다", emoji: "🇨🇦" },
    { shortcut: "/브라질", emoji: "🇧🇷" },
    { shortcut: "/인도", emoji: "🇮🇳" },
    { shortcut: "/멕시코", emoji: "🇲🇽" },
    { shortcut: "/남아공", emoji: "🇿🇦" },
    { shortcut: "/알바니아", emoji: "🇦🇱" },
    { shortcut: "/알제리", emoji: "🇩🇿" },
    { shortcut: "/안도라", emoji: "🇦🇩" },
    { shortcut: "/앙골라", emoji: "🇦🇴" },
    { shortcut: "/아르헨티나", emoji: "🇦🇷" },
    { shortcut: "/오스트레일리아", emoji: "🇦🇺" },
    { shortcut: "/오스트리아", emoji: "🇦🇹" },
    { shortcut: "/아제르바이잔", emoji: "🇦🇿" },
    { shortcut: "/바하마", emoji: "🇧🇸" },
    { shortcut: "/바레인", emoji: "🇧🇭" },
    { shortcut: "/방글라데시", emoji: "🇧🇩" },
    { shortcut: "/벨기에", emoji: "🇧🇪" },
    { shortcut: "/볼리비아", emoji: "🇧🇴" },
    { shortcut: "/보츠와나", emoji: "🇧🇼" },
    { shortcut: "/브루나이", emoji: "🇧🇳" },
    { shortcut: "/불가리아", emoji: "🇧🇬" },
    { shortcut: "/캐나다", emoji: "🇨🇦" },
    { shortcut: "/칠레", emoji: "🇨🇱" },
    { shortcut: "/콜롬비아", emoji: "🇨🇴" },
    { shortcut: "/크로아티아", emoji: "🇭🇷" },
    { shortcut: "/체코", emoji: "🇨🇿" },
    { shortcut: "/덴마크", emoji: "🇩🇰" },
    { shortcut: "/도미니카", emoji: "🇩🇴" },
    { shortcut: "/에콰도르", emoji: "🇪🇨" },
    { shortcut: "/이집트", emoji: "🇪🇬" },
    { shortcut: "/에스토니아", emoji: "🇪🇪" },
    { shortcut: "/핀란드", emoji: "🇫🇮" },
    { shortcut: "/그리스", emoji: "🇬🇷" },
    { shortcut: "/헝가리", emoji: "🇭🇺" },
    { shortcut: "/아이슬란드", emoji: "🇮🇸" },
    { shortcut: "/인도네시아", emoji: "🇮🇩" },
    { shortcut: "/아일랜드", emoji: "🇮🇪" },
    { shortcut: "/이스라엘", emoji: "🇮🇱" },
    { shortcut: "/이집트", emoji: "🇪🇬" },
    { shortcut: "/이탈리아", emoji: "🇮🇹" },
    { shortcut: "/자메이카", emoji: "🇯🇲" },
    { shortcut: "/요르단", emoji: "🇯🇴" },
    { shortcut: "/케냐", emoji: "🇰🇪" },
    { shortcut: "/쿠웨이트", emoji: "🇰🇼" },
    { shortcut: "/라트비아", emoji: "🇱🇻" },
    { shortcut: "/레바논", emoji: "🇱🇧" },
    { shortcut: "/리투아니아", emoji: "🇱🇹" },
    { shortcut: "/룩셈부르크", emoji: "🇱🇺" },
    { shortcut: "/말레이시아", emoji: "🇲🇾" },
    { shortcut: "/몰디브", emoji: "🇲🇻" },
    { shortcut: "/몰타", emoji: "🇲🇹" },
    { shortcut: "/모나코", emoji: "🇲🇨" },
    { shortcut: "/몽골리아", emoji: "🇲🇳" },
    { shortcut: "/네덜란드", emoji: "🇳🇱" },
    { shortcut: "/뉴질랜드", emoji: "🇳🇿" },
    { shortcut: "/노르웨이", emoji: "🇳🇴" },
    { shortcut: "/파나마", emoji: "🇵🇦" },
    { shortcut: "/파라과이", emoji: "🇵🇾" },
    { shortcut: "/페루", emoji: "🇵🇪" },
    { shortcut: "/필리핀", emoji: "🇵🇭" },
    { shortcut: "/폴란드", emoji: "🇵🇱" },
    { shortcut: "/포르투갈", emoji: "🇵🇹" },
    { shortcut: "/카타르", emoji: "🇶🇦" },
    { shortcut: "/루마니아", emoji: "🇷🇴" },
    { shortcut: "/세르비아", emoji: "🇷🇸" },
    { shortcut: "/싱가포르", emoji: "🇸🇬" },
    { shortcut: "/슬로바키아", emoji: "🇸🇰" },
    { shortcut: "/슬로베니아", emoji: "🇸🇮" },
    { shortcut: "/남아프리카공화국", emoji: "🇿🇦" },
    { shortcut: "/스웨덴", emoji: "🇸🇪" },
    { shortcut: "/스위스", emoji: "🇨🇭" },
    { shortcut: "/대만", emoji: "🇹🇼" },
    { shortcut: "/태국", emoji: "🇹🇭" },
    { shortcut: "/튀니지", emoji: "🇹🇳" },
    { shortcut: "/터키", emoji: "🇹🇷" },
    { shortcut: "/우크라이나", emoji: "🇺🇦" },
    { shortcut: "/아랍에미리트", emoji: "🇦🇪" },
    { shortcut: "/베네수엘라", emoji: "🇻🇪" },
    { shortcut: "/베트남", emoji: "🇻🇳" },
  ],
};

export const EMOJI_MAP: { [key: string]: string } = {};
Object.values(EMOJI_CATEGORIES).forEach(category => {
  category.forEach(item => {
    EMOJI_MAP[item.shortcut] = item.emoji;
  });
});
